llm_to_be_evaluated:
  provider: 'ollama'
  model: 'llama3'

llm_judge:
  provider: 'openai'
  model: 'gpt-4o-mini'

embedding:
  provider: 'openai'
  model: 'text-embedding-3-small'

vectorstore:
  chunk_size: 500
  chunk_overlap: 50
