llm_to_be_evaluated:
  provider: 'ollama'
  model: 'llama3'
  max_tokens: 2000
  temperature: 0.0

ragas_helper_llm:
  provider: 'openai'
  model: 'gpt-4o-mini'
  max_tokens: 2000
  temperature: 0.0

embeddings:
  provider: 'openai'
  model: 'text-embedding-3-small'

test:
  metrics: [faithfulness, answer_similarity, context_precision]