eval_llm:
  provider: 'oci'
  model_id: 'cohere.command-r-plus'

embeddings:
  provider: 'oci'
  model_id: 'cohere.embed-multilingual-v3.0'

test:
  metrics: [faithfulness, answer_similarity, context_precision]
  doc_format: pdf  # use 'mixed' if there are multiple formats